import React from "react";
import { navigate } from "@reach/router";
import { Formik, Field, Form } from "formik";

function AddTodo() {
    const handleSubmit = values => {
        const requestTodos = async () => {
            // Get the CSRF token generated by Rails to send it
            // as a header in the request to create a new to-do,
            // so that Rails will recognize the request as valid.
            const csrfToken = document.querySelector("meta[name=csrf-token]").content;
            const response = await fetch("/api/todos", {
                method: "POST",
                credentials: "include",
                headers: {
                    "Content-Type": "application/vnd.api+json",
                    "X-CSRF-Token": csrfToken,
                },
                body: JSON.stringify({ data: values}),
            });
            if (response.status === 201) {
                navigate("/");
            }
        }
        requestTodos();
    };

    return (
        <div>
            <h2>Add your To Do item</h2>
            <Formik
                initialValues={{
                    type: "todos",
                    attributes: {
                        title: "",
                        body: "",
                    },
                }}
                onSubmit={handleSubmit}
                render={() => (
                    <Form>
                        <Field type="text" name="attributes.title" />
                        <Field type="text" name="attributes.body" />

                        <button type="submit">Add</button>
                    </Form>
                )}
            />
        </div>
    );
}

export default AddTodo;
